name: ChatManager
version: '${project.version}'
main: me.jqrtox.chatmanager.ChatManager
api-version: '1.21'
commands:
  msg:
    aliases:
      - message
  chatcolor:
    aliases:
      - chatcolour
      - chatcolors
      - chatcolours
  settag:
    permission: rank.settag
    aliases:
      - tagset
  erasetag:
    permission: rank.erasetag
    aliases:
      - tagerase
  staffchat:
    permission: staff.chat
    aliases:
      - sc
  adminchat:
    permission: admin.chat
    aliases:
      - ac
  testinventory:
    permission: admin.testinventory

